### ISSUE TITLE
Build fails on XCode 7.2.1

### ISSUE THREAD

**Issue by kevinSuttle** [BohemianCoding/Coma#12]
`ECLogging/ECLoggingDebug.pch not found`

<img width="1512" alt="screen shot 2016-03-16 at 5 24 56 pm" src="https://cloud.githubusercontent.com/assets/95672/13829191/1126c43a-eb9c-11e5-8689-6d1370d50c7f.png">

**Comment by whakkee** [comment]
no one cares about Xcode 7.2.1 anymore, closing
